server:
  port: 8761
spring:
  application:
    name: xl-eurekaserver
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
